env:
    TERM: alacritty
font:
  normal:
    family: "HackNerdFont"
    style: Regular
  bold:
    family: "HackNerdFont"
    style: Bold

  italic:
    family: "HackNerdFont"
    style: Italic

  size: 12
