alias lofi='mpv --no-video https://youtu.be/jfKfPfyJRdk'
alias deadmau5='mpv --no-video https://youtu.be/0DJ-mEAEnrM'
alias ochentas='mpv --no-video https://youtu.be/e_Z1CawQIvo'
alias the_clash='mpv --no-video https://youtu.be/l0Q8z1w0KGY'
alias youtube_search='BROWSER=w3m ddgr -x -w youtube.com'
alias jajacker_lofi='mpv --no-video https://youtu.be/QifY_BtOxR8'
alias the_runaways='mpv --no-video https://youtu.be/cn_5WwhB_yA'
alias the_white_stripes='mpv --no-video "https://youtube.com/playlist?list=PLMEZyDHJojxPJyMyWb4jgc-ieKbr2hIVZ"'
alias ameli_lens='mpv --no-video https://youtu.be/9OtQpDypvBY'
alias fito_tercer_mundo='mpv --no-video https://youtu.be/92bu97IgE2E'
alias hack_net='mpv --no-video https://youtu.be/BEimFoWRXCw'
alias mr_s01='mpv --no-video https://youtu.be/hicayypkI7g'
alias mr_s03='mpv --no-video https://youtu.be/P0sAYxS03i0'
alias mr_s04='mpv --no-video https://youtu.be/QTp-cI-STUc'
